version: '3'

volumes:
  cache:

services:
    mopidy_prepare:
      image: whatever4711/mopidy:amd64
      user: root
      volumes:
        - ./local:/var/lib/mopidy/local
        - cache:/var/lib/mopidy/.local/share/mopidy
      entrypoint:
        - chown
        - -R
        - mopidy:audio
        - /var/lib/mopidy/

    mopidy_scan:
      image: whatever4711/mopidy:amd64
      volumes:
        - ./media:/var/lib/mopidy/media:ro
        - ./local:/var/lib/mopidy/local
        - cache:/var/lib/mopidy/.local/share/mopidy
      entrypoint:
        - mopidy
        - local
        - scan

  mopidy:
    image: whatever4711/mopidy:arm64v8
    depends_on:
      - icecast
    build:
      context: ./mopidy
      dockerfile: Dockerfile.arm64v8
#    environment:
      #- PULSE_COOKIE_DATA="$(pax11publish -d | grep --color=never -Po '(?<=^Cookie: ).*')"
      #- PULSE_SERVER="tcp:$(hostname -i):4713"
    ports:
      - "6600:6600"
      - "6680:6680"
    volumes:
      - ./media:/var/lib/mopidy/media:ro
      - ./local:/var/lib/mopidy/local
      - cache:/var/lib/mopidy/.local/share/mopidy
    #stdin_open: true
    #tty: true
    #entrypoint: /bin/bash
    #command: mopidy

  icecast:
    image: whatever4711/icecast:arm64v8
    build:
      context: ./icecast
      dockerfile: Dockerfile.arm64v8
    ports:
      - "8000:8000"
